email.send.from: noreply@abcmapp.com
email.send.to: support@ablepay.in 
#support@ablepay.in 
email.send.bcc: support@abcmapp.com,krushna.dakale@abcmapp.dev
#support@abcmapp.com


email.lowBalance.template.path: /opt/tomcat/webapps/view-kyc/WEB-INF/classes/static/e-KYCEmailTemplate/eKyc-lowallet-balance.html
#C://KYCGIT//abcm-kyc-service-ui//src//main//resources//static//e-KYCEmailTemplate//eKyc-lowallet-balance.html
#/opt/apache-tomcat-10.1.28_ablepay/webapps/abcm-adhar-api/WEB-INF/classes/static/e-KYCEmailTemplate/eKyc-lowallet-balance.html
#C://KYCGIT//abcm-aadhaar-api//src//main//resources//static//e-KYCEmailTemplate//eKyc-lowallet-balance.html
email.send.api.url: https://enotification.chatnpay.com/email/withmailer/sendEmailWithAttachmentWithCc
email.lowbalance.subject: Low Wallet Balance – Urgent Action Required to Avoid Service Disruption





#Local
#EsignApi: http://localhost:8049/api/v1/eSignAadhaar/verify
#EsignReport: http://localhost:8049/api/esign/report
#Esign-api-url: http://localhost:8049

#UAT
#EsignApi: http://203.192.228.125:1002/abcm-esign-api/api/v1/eSignAadhaar/verify
#EsignReport: http://203.192.228.125:1002/abcm-esign-api/api/esign/report
#Esign-api-url: http://203.192.228.125:1002/abcm-esign-api


#LIVE
EsignApi: https://ekyc.ablepay.in/abcm-esign-api/api/v1/eSignAadhaar/verify
EsignReport: https://ekyc.ablepay.in/abcm-esign-api/api/esign/report
Esign-api-url: https://ekyc.ablepay.in/abcm-esign-api




#Esign Webhook

#Local
#webhookUrl: http://localhost:8087/esign/webhook

#UAT
#webhookUrl: http://203.192.228.125:1002/view-kyc/esign/webhook

#LIVE
webhookUrl: https://ekyc.ablepay.in/view-kyc/esign/webhook



